version: '3.8'

services:
  mysqlpro:
    container_name: mysqlpro
    image: mysql:latest
    ports:
      - "33063:3306"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/provision/mysql/init:/docker-entrypoint-initdb.d
    environment: 
      MYSQL_ROOT_PASSWORD: admin123

  api:
    container_name: cleanarch-API-pro
    depends_on:
      - mysqlpro
    image: ${DOCKER_REGISTRY-}cleanarchapi
    environment:
      - ASPNETCORE_ENVIRONMENT=PRO
    build:
      context: .
      dockerfile: cleanarch-API/Dockerfile
    ports:
      - "7000:8080" #HOST_PORT:CONTAINER_PORT
      - "7001:8081" #HOST_PORT:CONTAINER_PORT
