version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    #environment:
    #  - REDIS_PASSWORD=admin123
    #command: ["redis-server", "--requirepass", "admin123", "--loglevel", "debug"]
    command: ["redis-server", "--loglevel", "debug"]
    ports:
      - "63790:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data:
